### ISSUE TITLE
[Enhancement] Markdown support

### ISSUE THREAD

**Issue by guivnf** [mortuusars/Scholar#4]
So one cool thing that i think would bring scholar to a whole new level would be to have some kind of markdown support, so users can add images, change text font color, edit characters as they see by making it bold, italic or anything like that. I think it'd be nice to have some kind of markdown support to a certain degree.

**Comment by mortuusars** [comment]
Since Scholar uses vanilla book system, this is not really doable. Having markdown support would be nice, but that basically would require full rewrite of the mod. And support for images is another layer of headache on top of that. 
And since there is already support for formatting (not the best but still), markdown would just be slight usability enchancement costing hefty amount of work.

**Comment by guivnf** [comment]
> Since Scholar uses vanilla book system, this is not really doable. Having markdown support would be nice, but that basically would require full rewrite of the mod. And support for images is another layer of headache on top of that. And since there is already support for formatting (not the best but still), markdown would just be slight usability enchancement costing hefty amount of work.

Oh yeah ic, well it was just something that crossed my mind, maybe i'll fork this and do some lingering to see how hard it turns out to be, thanks for the quick answer :)
